# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66e9c0a4135c1756bfed10a9591b8f333ee76cc8e74afaba9b337bba2e1ab526c55f469fcedf58bafe56639cffebfeadc7c0272ceff400c56e49c58a00add671

test:
  secret_key_base: 004b55b71d2d54fb1c01f1f7f79d2498d8f50f5e19d4cb7b3cdc5e3c3d01179049d5205c7d36b098f7f2ac54e51d2bfa470431dc83dbfd58d82048682bbc2135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
